version: '3.6'

services:
  redis:
    image: redis:5.0.7-alpine
    # container_name: spot-redis
    restart: always
    networks:
      - ${INTERNAL_NETWORK_NAME}
    command: redis-server --maxmemory 8G --maxmemory-policy allkeys-lru

  spot:
    image: ${CI_REGISTRY_IMAGE}:${SPOT_DOCKER_TAG}
    build:
      context: .
      dockerfile: Dockerfile
    logging: 
      driver: syslog
      options:
          tag: docker-${ENVIRONMENT_NAME}-spot-app
    restart: always
    networks:
      - ${INTERNAL_NETWORK_NAME}
    environment:
      SEARX_SECRET: "${SEARX_SECRET}"
      SEARX_PROXY_HTTP: "${SEARX_PROXY_HTTP}"
      SEARX_PROXY_HTTPS: "${SEARX_PROXY_HTTPS}"
      SEARX_REDIS_HOST: "${SEARX_REDIS_HOST}"
      SEARX_UI_DEFAULT_THEME: "${SEARX_UI_DEFAULT_THEME}"
      GUNICORN_LOGGER: 1
      GUNICORN_LEVEL: INFO
      NODE_NAME: "${NODE_NAME}"
      SENTRY_DSN: "${SENTRY_DSN}"
      SENTRY_TRACES_SAMPLE_RATE: "${SENTRY_TRACES_SAMPLE_RATE}"
      ENVIRONMENT_NAME: "${ENVIRONMENT_NAME}"

  spot-nginx:
    image: nginx:1.23
    restart: always
    logging: 
      driver: syslog
      options:
          tag: docker-${ENVIRONMENT_NAME}-spot-nginx
    networks:
      - ${INTERNAL_NETWORK_NAME}
    volumes:
      - ./etc/nginx/conf.d/spot.conf:/etc/nginx/conf.d/default.conf
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf      
      - ./etc/nginx/proxy_spot_params:/etc/nginx/proxy_spot_params
      - ./searx/static:/var/www/spot/static

  filtron:
    image: dalf/filtron:latest
    restart: always
    command: -listen :3000 -rules /etc/filtron/rules.json -target spot-nginx
    networks:
      - ${INTERNAL_NETWORK_NAME}
      - spot-wireguarded
    ports:
      - ${WIREGUARD_IP}:${FILTRON_PORT}:3000
    volumes:
      - ./etc/filtron/rules.json:/etc/filtron/rules.json


networks:
  staging-spot-default:
    external: true
  spot-default:
    external: true
  spot-wireguarded:
    external: true
