version: '3.6'

x-logging:
  &default-logging
  options:
    max-size: '100m'
    max-file: '3'
  driver: json-file

services:
  redis:
    image: redis:5.0.7-alpine
    logging: *default-logging
    restart: unless-stopped
    command: redis-server --maxmemory 8G --maxmemory-policy allkeys-lru

  spot:
    image: ${CI_REGISTRY_IMAGE}:${SPOT_DOCKER_TAG}
    build:
      context: .
      dockerfile: Dockerfile
    logging: *default-logging
    restart: unless-stopped
    environment:
      SEARX_SECRET: "${SEARX_SECRET}"
      SEARX_PROXY_HTTP: "${SEARX_PROXY_HTTP}"
      SEARX_PROXY_HTTPS: "${SEARX_PROXY_HTTPS}"
      SEARX_REDIS_HOST: "${SEARX_REDIS_HOST}"
      SEARX_UI_DEFAULT_THEME: "${SEARX_UI_DEFAULT_THEME}"
      GUNICORN_LOGGER: 1
      GUNICORN_LEVEL: INFO
      NODE_NAME: ${NODE_NAME}

  filtron:
    image: dalf/filtron:latest
    logging: *default-logging
    restart: unless-stopped
    command: -listen :3000 -rules /etc/filtron/rules.json -target spot
    ports:
      - ${FILTRON_PORT}:3000
    volumes:
      - ./etc/filtron/rules.json:/etc/filtron/rules.json




